# Generated by Django 3.0.1 on 2019-12-27 20:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('Shirts', 'Shirts'), ('Sweaters', 'Sweaters'), ('Sport wears', 'Sport wears'), ('Outwears', 'Outwears'), ('Jeans', 'Jeans'), ('Pants', 'Pants')], max_length=48)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids'), ('U', 'Unisex')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='products')),
            ],
        ),
    ]
